# Minimal configuration for LLM Pharma (Hydra compatible)

models:
  agent_models:
    # - id: mistral-saba-24b
      # provider: groq
    - id: meta-llama/llama-4-maverick-17b-128e-instruct # not stable for structured output
      provider: groq  
    - id: meta-llama/llama-4-scout-17b-16e-instruct # not stable for structured output
      provider: groq  
    # - id: llama3-8b-8192
    #   provider: groq
  tool_models:
    - id: moonshotai/kimi-k2-instruct
      provider: groq
    - id: qwen/qwen3-32b
      provider: groq  # fast
    - id: llama-3.3-70b-versatile
      provider: groq  # Slow
    - id: llama3-70b-8192
      provider: groq  # Slow
    - id: deepseek-r1-distill-llama-70b
      provider: groq  # Slow
    # - id: gemma2-9b-it
    #   provider: groq  # tool fails
    # - id: llama-3.1-8b-instant
    #   provider: groq  # tool fails
    # - id: llama3-8b-8192
    #   provider: groq  # tool fails
    # - id: gpt-3.5-turbo
    #   provider: openai
  temperature: 0.0

directories:
  data: data
  vector_store: vector_store
  sql_server: sql_server
  source_data: source_data  

files:
  policy_markdown: source_data/instut_trials_policy.md
  trials_csv: data/trials_data.csv
  disease_mapping: source_data/disease_mapping.json

# Add more config sections as needed 